name: CI/CD Docker Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du code source
      uses: actions/checkout@v4

    - name: Connexion au registre Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Construction de l'image (Build)
      # On attache ton pseudo Docker au nom de l'image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mon-api-cloud:latest .
      
    - name: Envoi de l'image (Push)
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mon-api-cloud:latest

    - name: Validation
      run: echo "🚀 L'image Docker a été publiée avec succès sur Docker Hub !"